name: application
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  window_manager: ^0.3.5
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/static/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat/static/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/static/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat/static/Montserrat-Bold.ttf
          weight: 700

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/static/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter/static/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter/static/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter/static/Inter-Bold.ttf
          weight: 700
  assets:
    - assets/images/
    - assets/navbar/

  uses-material-design: true
